name: deploy-logic-app
parameters:
- name: azureServiceConnection
  type: string
  default: '$(connection)'
variables:
  - template: ./global.yml
  - name: 'location'
    value: 'uksouth'
  - name: templateFile
    value: '$(Build.SourcesDirectory)/bicep/apibackendpool.bicep'
  - name: csmParametersFile
    value: '$(Build.SourcesDirectory)/bicep/apibackendpool.dev.bicepparam'
  - group: 'ais-connection-vars-dev'
trigger: none
resources:
  pipelines:
  - pipeline: package-logic-app-mbe-backend
    source: package-logic-app-mbe-backend
stages:
  - stage: Dev
    jobs:
    - deployment: Dev_Deploy
      pool:
        vmImage: $(vmImageName)
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: deploy.yml
              parameters:
                logicAppName: 'la-mbebackend-dev'
                artifactName: '$(artifactName)'
                serviceConnectionName: $(connection)
                logicAppBuildPipelineLabel: $(logicAppBuildPipelineLabel)
            - task: AzureResourceManagerTemplateDeployment@3.243.1
              inputs:
                deploymentScope: 'Resource Group'
                ConnectedServiceName: '${{ parameters.azureServiceConnection }}'
                SubscriptionName: '8af392db-423c-49d9-8c34-cdafbe702315' #This var is from the library
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'rg-apim-aisv31-dev' 
                location: '$(location)'
                templateLocation: 'Linked artifact'
                csmFile: '$(templateFile)'
                csmParametersFile: '$(csmParametersFile)'
                #overrideParameters: '-storageAccountType Standard_LRS'
                deploymentMode: 'Incremental'
                deploymentName: 'DeployPipelineTemplate'
