name: deploy-logic-app
parameters:
- name: azureServiceConnection
  type: string
  default: '$(connection)'
variables:
  - template: ./global.yml
  - name: 'location'
    value: 'uksouth'
  #- name: templateFile
  #  value: '$(Build.SourcesDirectory)/bicep/apimlogicapp.bicep'
  #- name: csmParametersFile
  #  value: '$(Build.SourcesDirectory)/bicep/apimlogicapp.dev.bicepparam'
  - group: 'ais-connection-vars-dev'
trigger: none
resources:
  pipelines:
  - pipeline: package-logic-app-mbe-backend
    source: package-logic-app-mbe-backend
stages:
  - stage: Dev
    jobs:
    - deployment: Dev_Deploy
      pool:
        vmImage: $(vmImageName)
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: deploy.yml
              parameters:
                logicAppName: 'la-mbebackend-dev'
                artifactName: '$(artifactName)'
                serviceConnectionName: $(connection)
                logicAppBuildPipelineLabel: $(logicAppBuildPipelineLabel)
